<? include('templates/other/top.phtml');?>
			<div class="sectionbig">
				<div class="section-title">
					<a href="interviews"><img src="images/home/interviews.png" alt="interviews - Questions & answers to designers and musicians"></a>
				</div>

                                <p>
                                    <strong>Bartek Jagniątkowski</strong> -
                                    On Mafia Wars known as Don Stefano, positively kicked senior art director at MRM Worldwide, list customer's list includes: loreal, volvo, opel, samsung, wedel, mastercard, orange ...  He found some time to share answers on few twisted questions.
                                    <br /><a href="http://jagniatkowski.net/">http://jagniatkowski.net/</a><br /><br />
                                    <div style="width: 563px; text-align:center;">
                                        <img src="images/interviews/bartek2.jpg" alt="Bartek Jagniątkowski"  />
                                    </div>
                                </p>

				<div class="boxbig-interviews-question">
					First off ...hello .. how are you? I haven't heard from you for ages. Thanks so much for taking  the time to answer some questions for new Digitalica readers ;)
				</div>

				<div class="boxbig-interviews-answer">
					It's been a while, that's true. I'm pretty well, thank you, just older, not much wiser though :) <br />
                                        Life's been treating me pretty good, I can't really complain - although there were some pretty rough times, all in all it turned out fine.
				</div>

				<div class="boxbig-interviews-question">
					Good designers learn and improve over time. What are some of the important lessons you've learned along the way?
				</div>

				<div class="boxbig-interviews-answer">
					That I can do almost anything :) When you set your sights on a goal and you commit to that goal, there's nothing to stop you. I like to think about myself as a renaissance man because of the many, many things that interest me and the scope of knowledge I amassed over all those years - it might not be very thorough, mind you, but there just so little time in one day :) But when I got back to Warszawa for the second time in my life and started working at MRM Worldwide, I thought I wanted to only do my pixels, nothing else. Then I got challenged with other aspects of the agency work - client related, project management related, accounting even - I was sure to fail. But I didn't, I learned a lot and got a new perspective on my own work, started to move in a direction I never thought I wanted to go.
				</div>

				<div class="boxbig-interviews-question">
					What's the best advice someone has given you?
				</div>

				<div class="boxbig-interviews-answer">
					If you grumble, you don't fuck :) I've spent quite some time with people, who gave me a new and much more simpler perspective on life that I used to have and i'm trying to stick to that "philosophy of simplicity" - to not overthink things. And to let things flow and follow that flow - not to stand against the current. Like a straw, bend with the wind to not break, but to stand up again when the wind stops. Something along those lines, at least :)
				</div>

				<div class="boxbig-interviews-question">
					Design theory and trends are constantly shifting and evolving. What do you think we'll see more of in 2012?
				</div>

				<div class="boxbig-interviews-answer">
					I can't really say, since i'm not really following trends too close. I've been seeing more and more simple and "typograhic" portfolios and webpages - nice, big headers with nice, big, clean body texts. But it must be my bad eyesight and aging taking the better of me :) It took years for us to come from pixel fonts in sizes below readability, really, to arrive to headers at 40-60 points in custom typeface size. I've always been an admirer of "less is more" doctrine and tried to follow that philosophy, now there are pretty neat tools to do that. I've seen pretty awesome things that use iPhones in connection with desktop computers to achieve a very ambient effect - I'd like to do more of that myself, to use many of the available tools and devices to connect them in one seamless project, to use Augmented Reality (although I HATE that term), there's still much to do on that field. <br />
                                        What I would really like to see is more "freedom from facebook" - lately I feel like people (meaning mostly clients) took Facebook for granted and turned it into "new internet" and everyone is "doing something on fb" - it's a great tool, but it's just a tool, not a solution to all your problems, for crying out loud. We've been laughing at the idea that in one or two years from now we're gonna go back to standalone pages on custom domain names and everyone will think it'll be such a fucking avantgarde thing to do, "you're not doing it on facebook? that's radical...". Pretty sad perspective.
				</div>

                                <div class="boxbig-interviews-question">
					Handmade or digital? choose one , and why?
				</div>

				<div class="boxbig-interviews-answer">
					Maybe I should say digital, but more and more I'd like to touch the stuff I do. I read books on my phone out of convenience, but I really prefer the printed thing, the smell of the paint, touch of paper, especially the old one - the same with art, I love what people are doing with pixels, but I'd like to hang that shit on my wall, you know? And I'm not talking about printed out on a laser plotter or something - I want it done by hand, on a real canvas or wood, with real paint and brush, I want it dirty, not really finished, rough and not so close to the line. You can't undo, yes, but the feeling is real :) You can redo though, over and over again, aiming for that perfection. Too bad I really suck at that myself, since I can't do shit on my own - draw or paint - but they say there's always time to learn. And I learn to appreciate art in general, but especially in non-digital form, for example recently I fell in love with Audrey Kawasaki's work - it's absolutely gorgeous.
				</div>

                                <div class="boxbig-interviews-question">
					If you could collaborate with one other artist, designer? who would it be?
				</div>

				<div class="boxbig-interviews-answer">
					I do collaborate with great artists on a daily basis, although the projects we work on are strictly commercial :) I've always wanted to work with Joshua Davis, but more as a apprentice, a fly-on-the-wall rather then a fellow designer, I want to know his secret, his tricks :) <br />
                                        Currently I'm working on an idea for a project that will support Infantile Spasms and Epilepsy Awareness foundation, I've already took part in production of two books they're selling on blurb.com and raising money to spread the word and educate on this rare and difficult condition. And I'll try to invite some of the best people I've met over the years to make it the most awesome shit there is - the cause is so right it has to work :)
				</div>
                            
                                <div class="boxbig-interviews-question">
					What are some of your favorite design blogs that you read?
				</div>

				<div class="boxbig-interviews-answer">
					I don't really :) I stopped following design blogs years ago and pretty much thought link sites died off - I was wrong, obviously :) And thank to gods for that. When I was doing some packaging stuff I've been reading thedieline.com and yankodesign.com all the time. Nowadays, I visit Behance on a daily basis - just to piss myself off, I guess, at the quality of work OTHER people do. The old classics, like surfstation, designiskinky... I don't, really - mostly because I just don't have the time.
				</div>
                            
                                <div class="boxbig-interviews-question">
                                    So, what's next...?
				</div>

				<div class="boxbig-interviews-answer">
                                    More work :) There are ideas coming in, there's lot to do still, another day, another challenge... There's this project for Infantile Spasm foundation, I've been talking with Jedrek Kostecki about some things we want to do together, I have a couple of photo projects on my mind, an idea for a desktop/iphone application... And since restless and unstoppable Wojtek Krosnowski is my CD, there's no telling when we're gonna stop - there's a LOT of shit going on :)
				</div>

                                <div class="boxbig-interviews-question">
                                    Thanks again, for doing this interview ;)
				</div>

				<div class="boxbig-interviews-answer">
                                    Not a problem, thanks :)
				</div>
                                
                                <br /><br />
                                <p>Interviewed by <a href="mailto:aneta(at)anetadesign.com">aneta(at)anetadesign.com</a></p>
                                <br />
                                <p><a href="interviews/">&laquo; Back to Interviews</a></p>
                                <br /><br />
                                <br /><br /><br /><br />



			</div>
<? include('templates/other/bottom.phtml');?>