<? include('templates/other/top.phtml');?>
			<div class="sectionbig">
				<div class="section-title">
					<a href="interviews"><img src="images/home/interviews.png" alt="interviews - Questions & answers to designers and musicians"></a>
				</div>
                            
                                <p>
                                    <strong>Greg Hojna ( G Kozakiewicz)</strong> 
                                    <br /><br />
                                    <div style="width: 563px; text-align:center;">
                                        <img src="images/interviews/greg2.jpg" alt="Greg Hojna"  />
                                    </div>
                                </p>                            

<div class="boxbig-interviews-question">
    1. Hi Greg , thank you so much for participating in this interview. I have been following you for some time and really respect what you do. Can you begin by telling us a little about your background? Where are you from and how did you get your start as a creative designer?
</div>

<div class="boxbig-interviews-answer">
    Thank you Aneta, much appreciated. I'm originally from Poland, however I left it seven years ago, traveled a little bit and this year moved to Edinburgh, Scotland to oversee design department at government organisation. <br />
    I'd say my creative journey started many years before I sat in the front of computer for a first time and drew the a line in LOGO. Twenty five years later you can find very similar system when drawing at canvas in HTML5, so if you haven't heard about the LOGO you are not loosing too much.
</div>

 
<div class="boxbig-interviews-question">
    2. Most of digitalica readers probably know you from your website: <a href="http://www.pencilrebel.com" target="_blank">www.pencilrebel.com</a> Tell us a little about your website. How did it come about? How did you initially envision this site and has its direction changed over time?
</div>

<div class="boxbig-interviews-answer">
    Well, yes, that was a long project and I did couple of one hours long speeches about it at FITC conferences and few other places however in this case with full respect I will make a long story short. Eight months, over 500 hours of work and massive amount of purest fun. Project with commercial value zero which turned out to win lot of awards and was one of the Top Performing games on Disney XD USA. <br />
    It was done in flash, which is great. I know a lot of people are now raving about "flash being dead" and it's true, flash is dead for sliding banners or full flash websites but ironically it is far away from being dead as environment for descent iphone apps. I've done it, it's great actually the hardest bit it getting certificate from apple. <br />
    Javascript on the over hand is promising too but for time being it's good for platform and tower defense type games but making something more flashy will be quite challenging. Let me bring here the answer of Seb Lee-Delisle regarding my question about CPU usage: "if your heating's broke, this would be a good way to replace it."<br />
</div>
                                
<div class="boxbig-interviews-question"> 
    3. What role has social media played in your website success?
</div>

<div class="boxbig-interviews-answer">
    In 2007/2008 social media did not play as massive role as it does today. Apart from that I spent L150 on this project so I would not have money for a huge social media campaign and sharing link via private channel with fb friends and twitter is useless, it won't make you famous or rich, you know it, don't you ? <br />
    You just need to live with the fact that there will always be cute kittens video that will have more hits on youtube than your best paid project. <br />
    Fact that Charlie Sheen has The Guinness World Record in "Fastest time to reach 1 million followers” (1m in 25hours) does it mean anyone will use his service in this area at all. <br />
    Very popular video by Giovanny Gutierrez who filmed his girlfriend bottom in the front of Wii did not get him a job at Nintendo. Actually that was a tricky one as Giovanny probably didn't know the fact that 80% of Wii users in USA are women. From the brand point of view, if you are not exhibitionist you won't feel comfortable with playing Wii when your man is at home. Would I employ him? Absolutely not as he completely doesn't know my audience. <br />
    Retweet my tweet to win an iPad sounds like a spam nowadays , doesn't it ? <br />
    So, social media are cool, but campaign will work if it's a part of bigger, well thought process. 
</div>
 
<div class="boxbig-interviews-question">
    4. Are you working on any exciting new projects that you would like to share with us?
</div>

<div class="boxbig-interviews-answer">
    Running my department is very exciting project every day. Working closely with development and three marketing departments is quite challenging. Stop motion animation is very close to my heart so I have few personal projects on the way, my first proper music video clip,  promo materials for well known business cards company and advert for well know internet browser. 
</div> 

<div class="boxbig-interviews-question">
    5. Handmade or digital? choose one , and why?
</div>

<div class="boxbig-interviews-answer">
    Handmade or digital ? That does not compute. Analog Input, Digital Output that works very well, always.
</div>
                                
<div class="boxbig-interviews-question">
    6. What’s the best advice someone has given you?
</div>

<div class="boxbig-interviews-answer">
    Keep calm and carry on? but that's from a poster. I don't know really, I don't think anyone ever did. In design industry, people are thinking too much about what others may think about them. It creates lot of constrains and mental blocks. Just follow common sense and do what you really want to do. If you do not have common sense in design and you do not know what you really want to achieve in this area, you should probably start coding. That will save you a lot of pain and disappointment.  <br />
    There is a plenty of great conferences in Europe, off the top of my head, FITC Amsterdam 2012 (<a href="http://www.fitc.ca/events/about/?event=125" target="_blank">http://www.fitc.ca/events/about/?event=125</a>), Beyond Tellerrand - Germany (<a href="http://play12.beyondtellerrand.com" target="_blank">http://play12.beyondtellerrand.com</a>) FOTB - UK (<a href="http://www.flashonthebeach.com/" target="_blank">http://www.flashonthebeach.com/</a>) - I had a word with John and it will come back this year 2012 with different name. OFFF - Spain (<a href="http://www.offf.ws/2012/" target="_blank">http://www.offf.ws/2012/</a>). It won't be cheap but get out yourself for one of these and it will change your life forever. 
</div>
                                
<div class="boxbig-interviews-question">
    7. So be creative... be unique... what does it mean for you?
</div>

<div class="boxbig-interviews-answer">
    That is a tricky question, I understand creative as a drive to create things which plays on emotions of targeted audience. To be unique means for me to do stuff which is different that current approved standard. The problem with this approach is you may be too creative for the type of clients your company works for or your style is too unique and you won't find a project, means, you earn no money. <br />
    Advice if I may, if you feel something is not like it should with your career, change a job every 1-2 years. It will improve and expand your skills as well as give you free rise in a salary. In your spare time do what you love to do until it becomes your job.
</div>


<div class="boxbig-interviews-question" style="font-weight: normal;">
    Thanks again, for doing this interview ;)
    Thank you and I hope all will work out well for everyone this year, all best. G.
</div>



                                <br /><br />
                                <p>Interviewed by <a href="mailto:aneta(at)anetadesign.com">aneta(at)anetadesign.com</a></p>
                                <br />
                                <p><a href="interviews/">&laquo; Back to Interviews</a></p>
                                <br /><br />
                                <br /><br /><br /><br />



			</div>
<? include('templates/other/bottom.phtml');?>