<? include('templates/other/top.phtml');?>
			<div class="sectionbig">
				<div class="section-title">
					<a href="interviews"><img src="images/home/interviews.png" alt="interviews - Questions & answers to designers and musicians"></a>
				</div>

                                <p>
                                    <strong>Jason Holland</strong> -
                                    He entered the world of digital design employment in 1995 and by 1997 (which brought me to London, UK) was forming his own agency with Felix Velarde. 
                                    <br /><br />
                                    <div style="width: 563px; text-align:center;">
                                        <img src="images/interviews/jason2.jpg" alt="Jason Holland"  />
                                    </div>
                                </p>



                                <div class="boxbig-interviews-question"> 1. What is your background in art? what you do now, where you live etc?</div>

                                <div class="boxbig-interviews-answer"> Always drawing as a kid, any kind of art was only a pastime until I turned
                                 to Graphic Design in the early 90's and studied this for 6 years in both
                                 Nottingham and Newcastle. It was almost by accident I turned my hand to
                                 digital design, and ended up producing the UK's first interactive CD ROM of
                                 all my fellow design graduate portfolios, which also appeared on the cover
                                 mounted disc with Creative Review Magazine. <br /><br />

                                 I entered the world of digital design employment in 1995 and by 1997
                                 (which brought me to London, UK) was forming my own agency with Felix
                                 Velarde. Underwired Amaze is our second agency and I am still the Creative
                                 Director (with an Art Director role included) with responsibility for not
                                 just design work, but also technical implementation (front end) and
                                 usability.
                                </div>

                                <div class="boxbig-interviews-question"> 2. Did you always want to become an art director, designer?</div>

                                 <div class="boxbig-interviews-answer">I always wanted to create and be creative. I think a passion for gadgets
                                 and computers brought me into digital design as I could do both things at
                                 the same time.
                                      </div>

                                 <div class="boxbig-interviews-question"> 3. So be creative... be unique...  what does it mean for you?   </div>

                                 <div class="boxbig-interviews-answer">It all about not doing the obvious or what has gone before. Just because a
                                 solution has been used by everyone, doesn't mean it's the best solution. I
                                 believe though that a true skill is being creative within the commercial
                                 environment and getting your client to share the passion for something new
                                 - even risky.
                                   </div>

                                 <div class="boxbig-interviews-question"> 4. How do you position yourself as a designer? Describe your 'style', like
                                 a good friend of yours would describe it.       </div>

                                 <div class="boxbig-interviews-answer">I am all about the detail. God (or the devil) is in the detail and it is
                                 what can turn a great design solution into a great one. Everything from a
                                 very subtle animation on a button, to how Apple design their products is
                                 all about the number of small elements that are both creative
                                 and re-thought for the end user. I'm also known for being able to spot
                                 something out of alignments by a pixel from across the room ;D
                                </div>

                                 <div class="boxbig-interviews-question"> 5. Which of your works has given you the most satisfaction?        </div>

                                 <div class="boxbig-interviews-answer">It is usually the project that has allowed a risky solution and produced
                                 amazing results. Even when it is just an email design, but it jumps out as
                                 a design that grabs your attention and makes you read it, click and
                                 interact with a brand. The likes of McCain has this quality, and even
                                 better when the products are in competition (inside your in box) with
                                 messages that most would consider much more interesting!
                                      </div>

                                <div class="boxbig-interviews-question"> 6. Sometimes it’s difficult to get started on a project, and brainstorm
                                 design ideas. How do you get inspired and stay motivated?   </div>

                                 <div class="boxbig-interviews-answer">I make sure I get creative input from as many sources as possible and from
                                 a very wide selection of media. For example, web sites are an obvious place
                                 to see great new work, but also looking at books and historic design. I'm
                                 loving retro at the moment :)
                                   </div>

                                <div class="boxbig-interviews-question">  7. What’s the best advice someone has given you?    </div>

                                 <div class="boxbig-interviews-answer">Don't worry about it.
                                </div>

                                <div class="boxbig-interviews-question"> 8. Design theory and trends are constantly shifting and evolving. What do
                                 you think we’ll see more of in 2012?      </div>

                                 <div class="boxbig-interviews-answer">A return to simplicity and making sure digital experiences work across all
                                 methods of viewing them, e.g. Computer, iPad, Mobile phone, TV, etc.
                                      </div>

                                <div class="boxbig-interviews-question"> 9. So what are you afraid of regarding the future?</div>

                                <div class="boxbig-interviews-answer"> I hope that 'digital' continues to become mainstream and not return to
                                 being a bolt-on. Gone are the days where offline design should dictate
                                 online solutions, and we shouldn't go back to that way of thinking.
                                       </div>

                                <div class="boxbig-interviews-question"> 10. When you are not designing or otherwise behind the computer, what do
                                 you enjoy doing to step away for a while? </div>

                                 <div class="boxbig-interviews-answer">I have two daughters ages 1 and 3, and they take up a lot of my time - and
                                 I enjoy every moment seeing how they grow - and yes, my eldest girl has an
                                 iPod touch packed with movies and games. When I get time to my self I love
                                 to take my Alfa Romeo for a drive on the twisty B-Roads (or even a track
                                 now and then) or sat at home playing on my Xbox.</div>

                                <br /><br />
                                <p>Interviewed by <a href="mailto:aneta(at)anetadesign.com">aneta(at)anetadesign.com</a></p>
                                <br />
                                <p><a href="interviews/">&laquo; Back to Interviews</a></p>
                                <br /><br />
                                <br /><br /><br /><br />



			</div>
<? include('templates/other/bottom.phtml');?>