<? include('templates/other/top.phtml');?>
			<div class="sectionbig">
				<div class="section-title">
					<a href="interviews"><img src="images/home/interviews.png" alt="interviews - Questions & answers to designers and musicians"></a>
				</div>
                            
				<div class="boxbig-interviews">

                                        <a href="interviews/Greg-Hojna">
                                            <img src="images/interviews/greg.jpg" alt="" class="bi-img-pink">
                                        </a>
					<div class="bi-text">
                                                <a href="interviews/Greg-Hojna" class="bi-text-name">Greg Hojna</a><br><br>
						<p></p> <br /> <a href="interviews/Greg-Hojna">see interview »</a>
					</div>
					<div class="clear"></div>
				</div>                             
				
				<div class="boxbig-interviews">

                                        <a href="interviews/Bartek-Jagniatkowski">
                                            <img src="images/interviews/bartek.jpg" alt="" class="bi-img-brown">
                                        </a>
					<div class="bi-text">
                                                <a href="interviews/Bartek-Jagniatkowski" class="bi-text-name">Bartek Jagniątkowski</a><br><br>
						<p>On Mafia Wars known as Don Stefano, positively kicked senior art director at MRM Worldwide. He found some time to share answers on few twisted questions. </p> <br /> <a href="interviews/Bartek-Jagniatkowski">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 
				
				<div class="boxbig-interviews last">
                                        <a href="interviews/Jason-Holland">
                                            <img src="images/interviews/jason.jpg" alt="" class="bi-img-pink">
                                        </a>
					
					<div class="bi-text">
                                                <a href="interviews/Jason-Holland" class="bi-text-name">Jason Holland</a><br><br>
						<p>He entered the world of digital design employment in 1995 and by 1997 (which brought me to London, UK) was forming his own agency with Felix Velarde. </p> <br />    <a href="interviews/Jason-Holland">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 								
				
			</div>
<? include('templates/other/bottom.phtml');?>