<? include('templates/other/top.phtml');?>
			<div class="sectionbig">
				<div class="section-title">
					<a href="about-digitalica"><img src="images/home/about-digitalica.png" alt="about-digitalica - 3 words describes Digitalica: design, music and fun"></a>
				</div>

				<div class="boxbig-news">
					<!--<div class="boxbig-news-header">
						<h1>about digitalica content</h1>
					</div>-->

                                        <p><b class="pink">Digitalica</b> was established in 2002 It was started from to passion for design and club music.</p>
                                        <p>
                                            "For hours, we literally looked at various pages with graphics and
                                            music which we wanted to share with others an  find out how many  other people have
                                            same passion as we have .
                                            3 words describes digitalica: design, music and fun.
                                            This is the online magazine for all those who like to think about good
                                            design, clubbing, who seeking  inspirations, new
                                            trends, and want to know what's happening in the world and want to
                                            present their creativity.
                                            Today digitalica is open for all the young artists and
                                            designer and is open to everyone because it's made in English version.
                                            Today, everyone can join the Digitalica, everyone who wants to share
                                            news, everyone who wants to tell their story through to what links to
                                            it inspired by. "<br />
                                            (Aneta)
                                        </p>
                                        <p>
                                            Old irreplaceable Digitalica's staff is represented by:<br />
                                            <br />
                                            <ul class="pink-ul">
                                                <li>Aneta Pertkiewicz (design)</li>
                                                <li>Igor Jankowski (music and design)</li>
                                                <li>Bartosz Kulesza (design)</li>
                                                <li>Wojtaszek (music)</li>
                                                <li>Naz (design)</li>
                                                <li>Evil Tom (music)</li>
                                            </ul>
                                            <br />
                                            Want to join the team or to present your art music, graphics?  it's simple, <a href="mailto:hello@digitalica.pl">contact us</a>.
                                        </p>
				</div>

			</div>
<? include('templates/other/bottom.phtml');?>