<? include('templates/other/top.phtml');?>
			<div class="sectionbig">
				<div class="section-title">
					<a href="designs"><img src="images/home/designs.gif" alt="designs - Strictly selected designs from whole internet"></a>
				</div>
				
				<div class="boxbig-interviews">
					<img src="images/tmp/interviews2.jpg" alt="" class="bi-img-brown">
					<a class="comments" href="#">9 comments</a>					
					<div class="bi-text">
						<span class="bi-text-name">Brodaty aka Bartek Jagniątkowski</span><br><br>
						<p><span class="pink">Fusce non magna</span> ac nisi ornare blandit. Proin tempor. Integer ullamcorper blandit nunc. Phasellus vitae massa id mi malesuada porta. </p> <a href="#">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 
				
				<div class="boxbig-interviews">
					<img src="images/tmp/interviews1.jpg" alt="" class="bi-img-pink">
					<span class="comments" href="#">no comment yet</span>
					<div class="bi-text">
						<span class="bi-text-name">Hejz</span><br><br>
						<p><span class="pink">Fusce non magna</span> ac nisi ornare blandit. Proin tempor. Integer ullamcorper blandit nunc. Phasellus vitae massa id mi malesuada porta. </p> <a href="#">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 				
				
				<div class="boxbig-interviews">
					<img src="images/tmp/interviews2.jpg" alt="" class="bi-img-brown">
					<a class="comments" href="#">9 comments</a>					
					<div class="bi-text">
						<span class="bi-text-name">Brodaty aka Bartek Jagniątkowski</span><br><br>
						<p><span class="pink">Fusce non magna</span> ac nisi ornare blandit. Proin tempor. Integer ullamcorper blandit nunc. Phasellus vitae massa id mi malesuada porta. </p> <a href="#">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 
				
				<div class="boxbig-interviews">
					<img src="images/tmp/interviews1.jpg" alt="" class="bi-img-pink">
					<span class="comments" href="#">no comment yet</span>
					<div class="bi-text">
						<span class="bi-text-name">Hejz</span><br><br>
						<p><span class="pink">Fusce non magna</span> ac nisi ornare blandit. Proin tempor. Integer ullamcorper blandit nunc. Phasellus vitae massa id mi malesuada porta. </p> <a href="#">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 								
				
				<div class="boxbig-interviews">
					<img src="images/tmp/interviews2.jpg" alt="" class="bi-img-brown">
					<a class="comments" href="#">9 comments</a>					
					<div class="bi-text">
						<span class="bi-text-name">Brodaty aka Bartek Jagniątkowski</span><br><br>
						<p><span class="pink">Fusce non magna</span> ac nisi ornare blandit. Proin tempor. Integer ullamcorper blandit nunc. Phasellus vitae massa id mi malesuada porta. </p> <a href="#">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 
				
				<div class="boxbig-interviews">
					<img src="images/tmp/interviews1.jpg" alt="" class="bi-img-pink">
					<span class="comments" href="#">no comment yet</span>
					<div class="bi-text">
						<span class="bi-text-name">Hejz</span><br><br>
						<p><span class="pink">Fusce non magna</span> ac nisi ornare blandit. Proin tempor. Integer ullamcorper blandit nunc. Phasellus vitae massa id mi malesuada porta. </p> <a href="#">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 				
				
				<div class="boxbig-interviews">
					<img src="images/tmp/interviews2.jpg" alt="" class="bi-img-brown">
					<a class="comments" href="#">9 comments</a>					
					<div class="bi-text">
						<span class="bi-text-name">Brodaty aka Bartek Jagniątkowski</span><br><br>
						<p><span class="pink">Fusce non magna</span> ac nisi ornare blandit. Proin tempor. Integer ullamcorper blandit nunc. Phasellus vitae massa id mi malesuada porta. </p> <a href="#">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 
				
				<div class="boxbig-interviews">
					<img src="images/tmp/interviews1.jpg" alt="" class="bi-img-pink">
					<span class="comments" href="#">no comment yet</span>
					<div class="bi-text">
						<span class="bi-text-name">Hejz</span><br><br>
						<p><span class="pink">Fusce non magna</span> ac nisi ornare blandit. Proin tempor. Integer ullamcorper blandit nunc. Phasellus vitae massa id mi malesuada porta. </p> <a href="#">see interview »</a>
					</div>
					<div class="clear"></div>
				</div> 					
				
			</div>
<? include('templates/other/bottom.phtml');?>