<? include('templates/other/top.phtml');?>
			<div class="sectionbig">
				<div class="section-title">
					<a href="faq"><img src="images/home/faq.png" alt="faq - What, where, how? Questions & answers"></a>
				</div>
                            
				<div class="boxbig-interviews-question">
					What DIGITALICA is and what to search at it?
				</div>
				
				<div class="boxbig-interviews-answer">
					Digitalica is an internet magazine focused on topic we are fascinated about and interested in on every day so mainly music and graphic design.
				</div>
				
				<div class="boxbig-interviews-question">
					How does it work?
				</div>
				
				<div class="boxbig-interviews-answer">
					To make things easier we devided content on fallowing groups:<br />
                                        
                                            - Design.stuff - The most up to date part of DIGITALICA. We present here design from all over the world.<br />
                                            - Sound.stuff - news from music and clubbing world.
                                        
				</div>
				
				<div class="boxbig-interviews-question">
					Can you write about my website in sound/design cattegory?
				</div>
				
				<div class="boxbig-interviews-answer">
					Sure, if your site match our estetic cryteria or make us interested in, we'll definately mention it. The get in touch with us using our contact form avaliable from the menu "Put your website in the air"
				</div>
				
				<div class="boxbig-interviews-question">
					I'm DJ/create my own music, is it possible to share it on DIGITALICA?
				</div>
				
				<div class="boxbig-interviews-answer">
					Yes, this should be no problem, get in touch with us and we'll take it from there.
				</div>

                                <div class="boxbig-interviews-question">
					I got in touch with you and sent you a link to my website but I can't find it in your news, why?
				</div>

				<div class="boxbig-interviews-answer">
					It is possible we have could different opinion and decided not to publish it in our news.
				</div>

                                <div class="boxbig-interviews-question">
					I wanted to talk with you about different things, for example cars ...
				</div>

				<div class="boxbig-interviews-answer">
					I think you are in wrong place, but if you feel like you definatelly have to do this, contact us, our mails are at the bottom of the screen
				</div>
				
									
				
			</div>
<? include('templates/other/bottom.phtml');?>