<? include('templates/top.phtml');?>
        <div id="content">
        	<div id="content-login">
                <h1><?=LANG_ZOSTALES_WYLOGOWANY?></h1>
                <br>
                <a href="<?=ADRES;?>">&lt; <?=LANG_POWROT_NA_STRONE?></a> &nbsp;&nbsp; | &nbsp;&nbsp;
                <a href="<?=SCRIPT;?>"><?=LANG_ZALOGUJ_PONOWNIE?> &gt;</a><br/><br/>
            </div>
        </div>
<? include('templates/bottom.phtml');?>